### ISSUE TITLE
Default value of result_screenshot_dir causes TypeError

### ISSUE THREAD

**Issue by ninz** [agramian/custom-text-test-runner#1]
```
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={'test_output_json': test_output_json}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/nini/repos/sine/venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/nini/repos/sine/venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "setup.py", line 41, in run_tests
    show_previous_results=True).run(test_modules).returnCode()
  File "build/bdist.linux-x86_64/egg/custom_text_test_runner/__init__.py", line 487, in run
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/nini/repos/sine/.eggs/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 673, in __call__
    return self.run(*args, **kwds)
  File "/home/nini/repos/sine/.eggs/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 641, in run
    result.addSuccess(self)
  File "build/bdist.linux-x86_64/egg/custom_text_test_runner/__init__.py", line 267, in addSuccess
  File "build/bdist.linux-x86_64/egg/custom_text_test_runner/__init__.py", line 255, in addScreenshots
  File "/home/nini/repos/sine/venv/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

`addScreenshots` uses `os.walk` which takes a string and throws an exception if None is passed. `result_screenshot_dir` is set to `None` as a default value in the constructor of `CustomTextTestRunner`. It should be something like `''`.

**Comment by agramian** [comment]
@ninz please create a PR and I'll release a new version on pypi
